export const styleList = [
  'background-color',
  'color',
  'opacity',
  'font-size',
  'font-family',
  'font-weight',
  'font-style',
  'text-decoration',
  'text-align',
  'width',
  'height',
  'display',
  'position',
  'transform',
  'z-index',
  'border-radius',
  'border'
];